### ISSUE TITLE
TypeError: Unexpected keyword argument {'n_jobs': -1}

### ISSUE THREAD

**Issue by rduke199** [bobbypaton/DBSTEP#22]
When I try to use the python API to find the buried volume for a given molecule, I get the error `TypeError: Unexpected keyword argument {'n_jobs': -1}`. Below is a sample code to show how I get this error. 
To install dbstep, I used `conda install -c conda-forge dbstep` and it installed version `1.0.0`. 

```
import urllib.request
import dbstep.Dbstep as db
url = "https://raw.githubusercontent.com/patonlab/DBSTEP/master/dbstep/examples/1Nap.xyz"
filename, headers = urllib.request.urlretrieve(url, filename="1Nap.xyz")
db.dbstep("1Nap.xyz", atom1=2, volume=True).bur_vol
```

**Comment by luchini18** [comment]
Hey @rduke199,

Thanks for spotting this, it's coming from a scipy module we use to measure volume that used to allow us to specify n_jobs. I hadn't realized in scipy versions 1.9+ they changed this argument from `n_jobs` to `workers`.

If you'd still like to use dbstep in the meantime you can downgrade to scipy==1.8 but I should have a new version out pretty soon!

**Comment by rduke199** [comment]
Thanks! I'll be looking forward to the new version.

**Comment by luchini18** [comment]
The issue should be fixed! This fix isn't on pip/conda yet but you can install the latest updates by downloading this repo and running `python setup.py install` 

Let me know if this works for you or if you have any other issues.
