### ISSUE TITLE
DBSTEP PyPi/conda not updated

### ISSUE THREAD

**Issue by Plasma-sol** [bobbypaton/DBSTEP#26]
Just wanted to enquire about a potential update to the DBSTEP PyPi and conda. The versions listed are 1.0 and still use the old scipy variable “n_jobs” instead of “workers”, unlike the latest version on github (DBSTEP 1.1.0). 
Many thanks and apologies if you are already aware of this.

**Comment by luchini18** [comment]
Hi @Plasma-sol
Thanks for the reminder! Pip and conda-forge should be updated now. 
Guilian
